# Russian (Russia) translations for PROJECT.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-09-04 18:37-0400\n"
"PO-Revision-Date: 2014-09-04 18:59-0400\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: ru_RU <LL@li.org>\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
"n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: gateone/applications/docker/app_docker.py:117
#, python-format
msgid "Active Docker Plugins: %s, "
msgstr "Активность Докер Плагины: %s , "

#: gateone/applications/docker/app_docker.py:220
msgid ""
"User is not allowed to use the docker application.  Skipping post-"
"authentication functions."
msgstr "Пользователь не имеет права использовать приложение Докер. Пропуск функции после аутентификации."

#: gateone/applications/docker/app_docker.py:295
msgid "The test_docker WebSocket action was called successfully!"
msgstr "Test_docker WebSocket действия назвали успешно!"

#: gateone/applications/docker/app_docker.py:297
#: gateone/applications/example/app_example.py:439
#, python-format
msgid "Here's what was recieved: %s"
msgstr "Вот то, что было получено: %s"

#: gateone/applications/docker/app_docker.py:331
msgid "// This is Gate One's Docker application settings file.\n"
msgstr "// Это Докер настройки приложения файл Gate One в. \ П"

#: gateone/applications/example/app_example.py:68
msgid "Doesn't do anything (just an example from the example app)."
msgstr "Ничего не делает (просто пример из примера приложения)."

#: gateone/applications/example/app_example.py:99
#, python-format
msgid "%s denied access to the 'test_example' function by policy.upn"
msgstr "%s лишены доступа к функции "test_example 'по policy.upn"

#: gateone/applications/example/app_example.py:154
#, python-format
msgid "%s denied access to the Example application by policy.upn"
msgstr "%s отказано в доступе к примеру заявления policy.upn"

#: gateone/applications/example/app_example.py:255
#, python-format
msgid "Active Example Plugins: %s, "
msgstr "Активность Пример Плагины: %s , "

#: gateone/applications/example/app_example.py:358
msgid ""
"User is not allowed to use the Example application.  Skipping post-"
"authentication functions."
msgstr "Пользователь не имеет права использовать пример приложения. Пропуск функции после аутентификации."

#: gateone/applications/example/app_example.py:437
msgid "The test_example WebSocket action was called successfully!"
msgstr "Test_example WebSocket действия назвали успешно!"

#: gateone/applications/example/app_example.py:473
msgid "// This is Gate One's Example application settings file.\n"
msgstr "// Это файл настройки Пример применения Gate One в. \ П"

#: gateone/applications/file_transfer/app_file_transfer.py:110
#: gateone/applications/terminal/policy.py:264
#, python-format
msgid "%s denied access to the Terminal application by policy.upn"
msgstr "%s отказано в доступе к Terminal заявления policy.upn"

#: gateone/applications/file_transfer/app_file_transfer.py:169
#, python-format
msgid "Active File Transfer Plugins: %s, "
msgstr "Активные Плагины передачи файлов: %s , "

#: gateone/applications/file_transfer/app_file_transfer.py:183
#: gateone/applications/terminal/app_terminal.py:280
msgid "Got exception trying to initialize the {0} plugin:"
msgstr "Получил исключение пытается инициализировать {0} плагин:"

#: gateone/applications/file_transfer/file_utils.py:36
msgid ""
"Could not import lzma module.  You probably need to run 'sudo pip install"
" backports.lzma'.  If you get errors you'll need to install the libzma-"
"dev package and re-run the pip command."
msgstr "Не удалось импортировать модуль LZMA. Вы, наверное, нужно запустить 'Судо пункт установить backports.lzma'. Если вы получаете ошибки, вам нужно будет установить пакет libzma-DEV и повторно запустить команду пипсов."

#: gateone/applications/file_transfer/file_utils.py:99
msgid "Removing because {path} is larger than {human_size}: {fp}"
msgstr "Удаление потому {путь} больше, чем {human_size}: {р}"

#: gateone/applications/file_transfer/file_utils.py:105
msgid "Could not delete {fp} ({e})"
msgstr "Не могу удалить {р} ({е})"

#: gateone/applications/file_transfer/file_utils.py:128
msgid "Removing file due to age (>{max_age} old): {file_path}"
msgstr "Удаление файла в силу возраста (> {max_age} старый): {file_path}"

#: gateone/applications/file_transfer/protocol.py:386
msgid "{instance_name}._process_queue(): No action registered for '{action}'"
msgstr "{Instance_name} ._ process_queue (): Никаких действий зарегистрированы для '{действие}'"

#: gateone/applications/file_transfer/protocol.py:393
msgid "{instance_name}._process_queue(): got invalid message: {message}"
msgstr "{Instance_name} ._ process_queue (): получил недопустимый сообщение: {сообщение}"

#: gateone/applications/file_transfer/plugins/protocol_dns/protocol_dns.py:95
msgid "Error: dnspython is not installed."
msgstr "Ошибка: dnspython не установлен."

#: gateone/applications/file_transfer/plugins/protocol_ftp/protocol_ftp.py:96
#: gateone/applications/file_transfer/plugins/protocol_ftp/protocol_ftp.py:136
msgid "Error retrieving {url}: {err}"
msgstr "Ошибка при получении {URL}: {эээ}"

#: gateone/applications/file_transfer/plugins/protocol_http/protocol_http.py:132
msgid "Fetching {log_url} ({human_size})"
msgstr "Выборка {log_url} ({human_size})"

#: gateone/applications/file_transfer/plugins/protocol_http/protocol_http.py:135
msgid "Error retrieving {log_url}: {err}"
msgstr "Ошибка при получении {log_url}: {эээ}"

#: gateone/applications/file_transfer/plugins/protocol_http/protocol_http.py:141
msgid "{log_url} fetched successfully."
msgstr "{Log_url} успешно принес."

#: gateone/applications/terminal/app_terminal.py:57
msgid ""
"If enabled, logs of user sessions will be saved in "
"<user_dir>/<user>/logs.  Default: Enabled"
msgstr "Если включен, журналы сеансов пользователей будут сохранены в <user_dir> / <пользователь> / журналы. По умолчанию: Включено"

#: gateone/applications/terminal/app_terminal.py:64
msgid "If enabled, logs of user sessions will be written to syslog."
msgstr "Если включен, журналы сеансов пользователей будут записаны в системный журнал."

#: gateone/applications/terminal/app_terminal.py:70
msgid ""
"Wrap terminals with dtach. Allows sessions to be resumed even if Gate One"
" is stopped and started (which is a sweet feature)."
msgstr "Оберните клеммы dtach. Позволяет сеансы должны быть возобновлено, даже если ворота Один остановлен и начал (который является сладким функция)."

#: gateone/applications/terminal/app_terminal.py:77
msgid "Kill any running Gate One terminal processes including dtach'd processes."
msgstr "Убейте любого, работающих ворота одного терминала процессы, включая dtach'd процессов."

#: gateone/applications/terminal/app_terminal.py:263
#, python-format
msgid "Active Terminal Plugins: %s, "
msgstr "Активность Терминал Плагины: %s , "

#: gateone/applications/terminal/app_terminal.py:406
msgid ""
"User is not allowed to use the Terminal application.  Skipping post-"
"authentication functions."
msgstr "Пользователь не имеет права использовать терминальное приложение. Пропуск функции после аутентификации."

#: gateone/applications/terminal/app_terminal.py:440
#: gateone/applications/x11/app_x11.py:720
msgid "Path to icon ({icon}) for command, '{cmd}' could not be found."
msgstr "Путь к иконке ({значок}) для команды, '{команда}' не может быть найден."

#: gateone/applications/terminal/app_terminal.py:511
msgid "You're missing the 'commands' setting!"
msgstr "Вы упускаете установку 'команды'!"

#: gateone/applications/terminal/app_terminal.py:530
#: gateone/applications/terminal/app_terminal.py:577
#, python-format
msgid "Bad font in fonts dir (missing Font Family in name table): %s"
msgstr "Плохой шрифта в шрифтов реж (отсутствует Семейство шрифтов в таблице имен): %s"

#: gateone/applications/terminal/app_terminal.py:803
msgid ""
"Warning: Terminals are closing too fast.  If you see this message "
"multiple times it is likely that the configured command is failing to "
"execute.  Please check your server settings."
msgstr "Предупреждение: Терминалы закрытия слишком быстро. Если вы видите это сообщение несколько раз вполне вероятно, что настроен команда не в состоянии выполнить. Пожалуйста, проверьте настройки сервера."

#: gateone/applications/terminal/app_terminal.py:813
#, python-format
msgid ""
"Terminals are closing too quickly after being opened (command: %s).  "
"Please check your 'commands' (usually in settings/50terminal.conf)."
msgstr "Терминалы закрытия слишком быстро после того, как открыл (команда: %s ). Пожалуйста, ознакомьтесь с «команды» (обычно в настройках / 50terminal.conf)."

#: gateone/applications/terminal/app_terminal.py:1030
#, python-format
msgid ""
"You are missing a 'default_command' in your terminal settings (usually "
"50terminal.conf in %s)"
msgstr "У вас не хватает 'default_command' в настройках терминала (обычно 50terminal.conf в %s )"

#: gateone/applications/terminal/app_terminal.py:1042
#, python-format
msgid "%s: Attempted to execute invalid command (%s)."
msgstr "%s : Попытка выполнить недопустимую команду ( %s )."

#: gateone/applications/terminal/app_terminal.py:1044
#, python-format
msgid "Terminal: Invalid command: %s"
msgstr "Терминал: Неверная команда: %s"

#: gateone/applications/terminal/app_terminal.py:1122
#, python-format
msgid "new_terminal cmd: %s"
msgstr "new_terminal CMD: %s"

#: gateone/applications/terminal/app_terminal.py:1186
msgid "WARNING: Logging is set to DEBUG.  All keystrokes will be logged!"
msgstr "ВНИМАНИЕ: Вход установлен в DEBUG. Все нажатия клавиш будут регистрироваться!"

#: gateone/applications/terminal/app_terminal.py:1218
msgid ""
"Invalid encoding.  For a list of valid encodings see:<br><a "
"href='http://docs.python.org/2/library/codecs.html#standard-encodings' "
"target='new'>Standard Encodings</a>"
msgstr "Неверный кодирования. Для получения списка допустимых кодировок смотрите: инструменты <a href='http://docs.python.org/2/library/codecs.html#standard-encodings' target='new'> Стандартный Кодировки </a>"

#: gateone/applications/terminal/app_terminal.py:1251
#, python-format
msgid "Invalid keyboard mode.  Must be one of: %s, "
msgstr "Неверный режим клавиатуры. Должен быть один из: %s , "

#: gateone/applications/terminal/app_terminal.py:1273
msgid "Error: Terminal {term} does not exist."
msgstr "Ошибка: Терминал {термин} не существует."

#: gateone/applications/terminal/app_terminal.py:1312
msgid "Error: Terminal {term} does not exist at the current location ({location})"
msgstr "Ошибка: Терминал {термин} не существует в текущем местоположении ({расположение})"

#: gateone/applications/terminal/app_terminal.py:1363
#, python-format
msgid "Incoming terminal from location: %s"
msgstr "Входящий терминал с места нахождения: %s"

#: gateone/applications/terminal/app_terminal.py:1602
#, python-format
msgid "WebSocket closed (%s)"
msgstr "WebSocket закрыты ( %s )"

#: gateone/applications/terminal/app_terminal.py:1656
#, python-format
msgid "KeyError in refresh_screen: %s"
msgstr "KeyError в refresh_screen: %s"

#: gateone/applications/terminal/app_terminal.py:1664
#, python-format
msgid "Invalid terminal number given to full_refresh(): %s"
msgstr "Неверный номер терминала уделено full_refresh (): %s"

#: gateone/applications/terminal/app_terminal.py:1766
#, python-format
msgid "Got exception trying to write_chars() to terminal %sterm"
msgstr "Получил исключение пытается write_chars () к клемме %s срока"

#: gateone/applications/terminal/app_terminal.py:1808
msgid "Got exception trying to execute plugin's optional ESC sequence handler..."
msgstr "Получил исключение пытается выполнить дополнительный обработчик последовательности ESC плагина ..."

#: gateone/applications/terminal/app_terminal.py:1824
#, python-format
msgid "Could not load bell: %s"
msgstr "Не удалось загрузить колокол: %s"

#: gateone/applications/terminal/app_terminal.py:1861
#: gateone/core/server.py:2534
msgid "send_css is false; will not send JavaScript."
msgstr "send_css ложно; не будет посылать JavaScript."

#: gateone/applications/terminal/app_terminal.py:2041
msgid "{upn} updated sharing permissions on terminal {term} ({title}))"
msgstr "{Сор} обновлены права совместного пользования на терминале {термин} ({название}))"

#: gateone/applications/terminal/app_terminal.py:2170
#, python-format
msgid "Share ID '%s' is already in use"
msgstr "Share ID ' %s 'уже используется"

#: gateone/applications/terminal/app_terminal.py:2183
msgid "{upn} changed share ID of terminal {term} from '{old}'' to '{new}'"
msgstr "{Сор} изменилось акций идентификатор терминала {перспективе} от '{старый}' 'в' {новый} '"

#: gateone/applications/terminal/app_terminal.py:2203
msgid "Error: Invalid share ID."
msgstr "Ошибка: Неправильно доля ID."

#: gateone/applications/terminal/app_terminal.py:2241
msgid "No terminal associated with the given share_id."
msgstr "Нет терминал, связанный с данным share_id."

#: gateone/applications/terminal/app_terminal.py:2352
msgid "Invalid share_id."
msgstr "Неверный share_id."

#: gateone/applications/terminal/app_terminal.py:2362
msgid "Requested shared terminal does not exist."
msgstr "Запрашиваемая поделился терминал не существует."

#: gateone/applications/terminal/app_terminal.py:2367
msgid "You are not authorized to view this terminal"
msgstr "Вы не авторизованы для просмотра этого терминал"

#: gateone/applications/terminal/app_terminal.py:2371
msgid "Invalid password."
msgstr "Неправильный пароль."

#: gateone/applications/terminal/app_terminal.py:2440
msgid "{upn} connected to terminal shared by {owner}"
msgstr "{Сор} подключен к терминалу разделяют {владелец}"

#: gateone/applications/terminal/app_terminal.py:2448
#, python-format
msgid "%s (%s) is now viewing terminal %s"
msgstr "%s ( %s ) в настоящее время просмотра терминала %s"

#: gateone/applications/terminal/app_terminal.py:2709
#: gateone/core/configuration.py:890
msgid "// This is Gate One's Terminal application settings file.\n"
msgstr "// Это Терминал файл настройки приложения Gate One в. \ П"

#: gateone/applications/terminal/app_terminal.py:2725
msgid "dtach command not found.  dtach support has been disabled."
msgstr "Команда dtach не найдено. dtach поддержка была отключена."

#: gateone/applications/terminal/app_terminal.py:2730
msgid ""
"The default path to known_hosts has been changed.  Please update your "
"settings to use '/.ssh/known_hosts' instead of '/ssh/known_hosts'.  "
"Applying a termporary fix..."
msgstr "Путь по умолчанию, чтобы known_hosts была изменена. Пожалуйста, обновите ваши настройки, чтобы использовать "/.ssh/known_hosts 'вместо' / SSH / known_hosts". Применение termporary исправить ..."

#: gateone/applications/terminal/app_terminal.py:2793
msgid "View terminal session logs."
msgstr "Посмотреть логи сеанса работы."

#: gateone/applications/terminal/policy.py:72
#, python-format
msgid ""
"%s denied opening new terminal.  The 'max_terms' policy limit (%s) has "
"been reached for this user."
msgstr "%s отрицал открытие нового терминала. Предел политика 'max_terms "( %s ) была достигнута для этого пользователя."

#: gateone/applications/terminal/policy.py:78
#, python-format
msgid "Server policy dictates that you may only open %s terminal(s) "
msgstr "Политика сервера подсказывает, что вы можете открыть только %s терминал (ы) "

#: gateone/applications/terminal/policy.py:119
msgid ""
"{upn} denied executing {function_name} by policy (not owner of terminal "
"or does not have write access)."
msgstr "{Сор} отказано выполнения {function_name} политикой (не владельца терминала или не имеет доступа на запись)."

#: gateone/applications/terminal/policy.py:167
#, python-format
msgid "%s denied sharing terminal by policy.upn"
msgstr "%s отрицал обмена терминал, policy.upn"

#: gateone/applications/terminal/policy.py:177
msgid "You do not have permission to write to this terminal."
msgstr "Вы не имеете разрешения на запись в этом терминале."

#: gateone/applications/terminal/term_utils.py:75
msgid "Error decoding {0}.  File will be removed."
msgstr "Декодирования Ошибка {0} . Файл будет удален."

#: gateone/applications/terminal/plugins/html/html.py:63
msgid "Raw HTML"
msgstr "Необработанный HTML"

#: gateone/applications/terminal/plugins/html/html.py:109
#, python-format
msgid "HTML Plugin: Sorry but the '%s' tag is not allowed."
msgstr "HTML Плагин: Извините, но ' %s 'тег не допускается."

#: gateone/applications/terminal/plugins/html/html.py:117
msgid "HTML Plugin: Sorry but using 'javascript:' is not allowed."
msgstr "HTML Плагин: Извините, но с использованием 'JavaScript:' не допускается."

#: gateone/applications/terminal/plugins/html/html.py:124
msgid "HTML Plugin: Sorry but using JavaScript events is not allowed."
msgstr "HTML Плагин: Извините, но с использованием события JavaScript не допускается."

#: gateone/applications/terminal/plugins/html/html.py:132
msgid "HTML Plugin: Sorry but using 'FSCommand' is not allowed."
msgstr "HTML Плагин: Извините, но с использованием 'FSCommand' не допускается."

#: gateone/applications/terminal/plugins/html/html.py:139
msgid "HTML Plugin: Sorry but using 'seekSegmentTime' is not allowed."
msgstr "HTML Плагин: Извините, но используя 'seekSegmentTime' не допускается."

#: gateone/applications/terminal/plugins/html/html.py:147
msgid "HTML Plugin: Sorry but using 'vbscript:' is not allowed."
msgstr "HTML Плагин: Извините, но с использованием 'VBScript:' не допускается."

#: gateone/applications/terminal/plugins/logging/logging_plugin.py:113
msgid ""
"NOTE: User session logging is disabled.  To enable it, set "
"'session_logging = True' in your server.conf."
msgstr "ПРИМЕЧАНИЕ: регистрация сессия пользователя отключен. Чтобы включить ее, установите 'session_logging = True' в вашем server.conf."

#: gateone/applications/terminal/plugins/logging/logging_plugin.py:121
msgid "NOTE: Your access to the log viewer has been restricted."
msgstr "ПРИМЕЧАНИЕ: Ваш доступ к программе просмотра протоколов было ограничено."

#: gateone/applications/terminal/plugins/logging/logging_plugin.py:323
#: gateone/applications/terminal/plugins/logging/logging_plugin.py:456
#: gateone/applications/terminal/plugins/logging/logging_plugin.py:575
msgid "ERROR: Log not found"
msgstr "ОШИБКА: Вход не найден"

#: gateone/applications/terminal/plugins/ssh/ssh.py:129
#, python-format
msgid "Renaming %s's 'ssh' directory to '.ssh'."
msgstr "Переименование %s 'с' SSH 'Каталог для' .ssh '."

#: gateone/applications/terminal/plugins/ssh/ssh.py:133
#, python-format
msgid ""
"Both an 'ssh' and '.ssh' directory exist for user %s.  Using the .ssh "
"directory."
msgstr "Оба 'SSH' и каталог '.ssh' существует для пользователя %s . Используя каталог .ssh."

#: gateone/applications/terminal/plugins/ssh/ssh.py:159
#: gateone/applications/terminal/plugins/ssh/ssh.py:168
msgid "SSH Plugin: Unable to open slave sub-channel."
msgstr "SSH Plugin: Невозможно открыть подчиненный подканал."

#: gateone/applications/terminal/plugins/ssh/ssh.py:264
msgid "SSH sub-channel closed due to inactivity."
msgstr "SSH суб-канал закрытым в результате простоя."

#: gateone/applications/terminal/plugins/ssh/ssh.py:276
#, python-format
msgid ""
"%s: Got an error trying to capture output inside of execute_command() "
"running: %s"
msgstr "%s : Получил ошибка при попытке захватить выход внутри execute_command () Летние: %s"

#: gateone/applications/terminal/plugins/ssh/ssh.py:285
msgid "Error: Timeout exceeded or command failed to execute."
msgstr "Ошибка: Тайм-аут превышен или команду выполнить не удалось."

#: gateone/applications/terminal/plugins/ssh/ssh.py:313
#, python-format
msgid "%s: Got an error trying to open sub-channel on term %s..."
msgstr "%s : Получена ошибка при попытке открыть суб-канал на срок %s ..."

#: gateone/applications/terminal/plugins/ssh/ssh.py:476
#, python-format
msgid "SSH Plugin Error: Invalid name given, %s"
msgstr "SSH Plugin Ошибка: Неверное имя дано, %s"

#: gateone/applications/terminal/plugins/ssh/ssh.py:495
#, python-format
msgid "SSH Plugin Error: Public key not found at %s"
msgstr "SSH Plugin Ошибка: Открытый ключ не найден в %s"

#: gateone/applications/terminal/plugins/ssh/ssh.py:524
msgid "Error:  You must supply a 'host'."
msgstr "Ошибка: Вы должны поставить "хозяин"."

#: gateone/applications/terminal/plugins/ssh/ssh.py:553
#, python-format
msgid "Error: Could not determine the fingerprint of %s:%s... '%s'"
msgstr "Ошибка: не удалось определить отпечаток %s : %s ... ' %s '"

#: gateone/applications/terminal/plugins/ssh/ssh.py:617
msgid "Keypair generation failed."
msgstr "Ключей поколение не удалось."

#: gateone/applications/terminal/plugins/ssh/ssh.py:623
#, python-format
msgid "There was a problem generating SSH keys: %s"
msgstr "Существовал проблема генерации ключей SSH: %s"

#: gateone/applications/terminal/plugins/ssh/ssh.py:641
msgid "Keypair generation complete"
msgstr "Ключей поколение полное"

#: gateone/applications/terminal/plugins/ssh/ssh.py:772
#, python-format
msgid "Error generating public key from private key at %s"
msgstr "Ошибка генерации открытого ключа из закрытого ключа на %s"

#: gateone/applications/terminal/plugins/ssh/ssh.py:841
msgid "You must specify a valid *name*."
msgstr "Вы должны указать действительный * имя *."

#: gateone/applications/terminal/plugins/ssh/ssh.py:848
msgid "No files were given to save!"
msgstr "Файлы не дали спасти!"

#: gateone/applications/terminal/plugins/ssh/ssh.py:869
msgid "ERROR: Private key is not valid."
msgstr "ОШИБКА: Секретный ключ не действителен."

#: gateone/applications/terminal/plugins/ssh/ssh.py:880
msgid "Got public key, cancelling public key generation timer."
msgstr "Получил открытый ключ, отменяя общественного таймер генерации ключей."

#: gateone/applications/terminal/plugins/ssh/ssh.py:891
msgid ""
"Only received a private key.  Setting timeout to generate the public key "
"if not received within 3 seconds."
msgstr "Только получил закрытый ключ. Установка тайм-аут, чтобы генерировать открытый ключ, если не получена в течение 3 секунд."

#: gateone/applications/terminal/plugins/ssh/ssh.py:909
#, python-format
msgid "Error saving keys: %s"
msgstr "Ошибка сохранения ключей: %s"

#: gateone/applications/terminal/plugins/ssh/ssh.py:936
#, python-format
msgid "Error deleting keypair: %s"
msgstr "Ошибка при удалении пара ключей: %s"

#: gateone/applications/terminal/plugins/ssh/ssh.py:1029
#, python-format
msgid "Error getting identities: %s"
msgstr "Ошибка при получении тождества: %s"

#: gateone/applications/terminal/plugins/ssh/ssh.py:1119
#, python-format
msgid "Error creating user's ssh directory: %s\n"
msgstr "Ошибка при создании каталога SSH пользователя: %s \ п"

#: gateone/applications/terminal/plugins/ssh/ssh.py:1145
#, python-format
msgid ""
"Could not set %s as executable.  You will need to 'chmod a+x' that script"
" manually."
msgstr "Не удалось установить %s как исполняемый файл. Вам нужно будет 'CHMOD а + х' этого сценария вручную."

#: gateone/applications/terminal/plugins/ssh/ssh.py:1148
msgid ""
"Error loading SSH plugin:  The ssh_connect.py script is not executable.  "
"See the logs for more details."
msgstr "Ошибка загрузки плагинов SSH: ssh_connect.py сценарий не является исполняемым. Можно найти в журналах для более подробной информации."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:263
#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:486
msgid "The port must be an integer < 65535"
msgstr "Порт должен быть целым числом <65535"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:337
msgid "The following SSH identities are being used for this connection:"
msgstr "Следующие SSH тождества используются для связи:"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:345
#, python-format
msgid "\t[1m%s[0m"
msgstr "\ Т [1m %s [0м"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:390
#, python-format
msgid ""
"]_;notice|Existing ssh session detected for ssh://%s@%s:%s; utilizing "
"existing tunnel."
msgstr "] _; Заметите | Существующие SSH сессия обнаружено SSH: // %s @ %s : %s ; используя существующие туннель."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:507
#, python-format
msgid "Error: Could not find telnet binary in path %r"
msgstr "Ошибка: не удалось найти телнет двоичный в пути% г"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:645
msgid ""
"Path to the ssh command.  Default: 'ssh' (which usually means "
"/usr/bin/ssh)."
msgstr "Путь к команде SSH. По умолчанию: 'SSH' (что обычно означает / USR / бен / SSH)."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:660
msgid "[Press Enter to close this terminal]"
msgstr "[Нажмите Enter, чтобы закрыть этот терминал]"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:665
msgid ""
"Any additional arguments that should be passed to the ssh command.  It is"
" recommended to wrap these in quotes."
msgstr "Любые дополнительные аргументы, которые должны быть переданы в команду SSH. Рекомендуется, чтобы обернуть их в кавычки."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:672
msgid ""
"Path to the control socket for connection sharing (see master mode and "
"'man ssh')."
msgstr "Путь к контрольной гнездо для совместного использования подключения (смотрите описание мастер режим и 'человек SSH')."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:680
msgid ""
"Enable the use of SSHFP in verifying host keys. See:  "
"http://en.wikipedia.org/wiki/SSHFP#SSHFP"
msgstr "Разрешить использование SSHFP в проверке ключи хостов. Смотреть: http://en.wikipedia.org/wiki/SSHFP#SSHFP"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:687
msgid "Enable the VisualHostKey (randomart hash host key) option when connecting."
msgstr "Включите VisualHostKey (randomart хэш ключа хоста) вариант при подключении."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:694
msgid "Display the logo image inline in the terminal."
msgstr "Отображение в линию логотип изображения в терминале."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:699
msgid "Provide the logo path (implies --logo)."
msgstr "Укажите путь логотип (подразумевает --logo)."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:704
msgid ""
"The default host that will be used for outbound connections if no "
"hostname is provided.  Default: localhost"
msgstr "Хост по умолчанию, который будет использоваться для исходящих подключений, если имя хоста не предоставляется. По умолчанию: локальный"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:711
msgid ""
"The default port that will be used for outbound connections if no port is"
" provided.  Default: 22"
msgstr "Порт по умолчанию, который будет использоваться для исходящих подключений, если порт не предусмотрен. По умолчанию: 22"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:718
msgid ""
"Skip asking for host information (hostname and port) and ask for "
"credentials only (you probably want to use --default_host and "
"--default_port as well)."
msgstr "Перейти с просьбой предоставить информацию хоста (хост и порт) и попросить полномочий только (вы, вероятно, хотите использовать --default_host и --default_port а)."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:785
msgid "Error:  You must enter a valid hostname or IP address."
msgstr "Ошибка: Вы должны ввести правильное имя хоста или IP-адрес."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:787
msgid "Error:  You must enter a valid port (1-65535)."
msgstr "Ошибка: Вы должны ввести правильный порт (1-65535)."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:789
msgid "Error:  You must enter a valid username."
msgstr "Ошибка: Вы должны ввести имя пользователя."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:801
#, python-format
msgid ""
"[Press Shift-F1 for help]\n"
"\n"
"Host/IP or ssh:// URL%s: "
msgstr "[Нажмите Shift-F1 за помощью] \ п \ nHost / IP или SSH: // URL %s : "

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:849
#, python-format
msgid "%s: "
msgstr "%s : "

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:874
#, python-format
msgid "Connecting to ssh://%s@%s:%s"
msgstr "Подключение к SSH: // %s @ %s : %s"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:894
#, python-format
msgid "Connecting to telnet://%s@%s:%s"
msgstr "Подключение к Telnet: // %s @ %s : %s"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:898
#, python-format
msgid "Connecting to telnet://%s:%s"
msgstr "Подключение к Telnet: // %s : %s"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:903
#, python-format
msgid "Unknown protocol \"%s\""
msgstr "Неизвестный протокол \ " %s \ ""

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:907
#, python-format
msgid "Got Exception: %s"
msgstr "Возникло исключение: %s"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:912
msgid "[Press any key to close this terminal]"
msgstr "[Нажмите любую клавишу, чтобы закрыть этот терминал]"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:916
msgid ""
"\n"
"User requested exit.  Quitting..."
msgstr "\ Нусер просил выйти. Выход ..."

#: gateone/applications/x11/app_x11.py:90
msgid ""
"If provided, will use the specified xorg.conf file when spawning "
"instances of Xorg."
msgstr "Если условии, будет использовать указанный файл xorg.conf, когда нереста экземпляры Xorg."

#: gateone/applications/x11/app_x11.py:328
#, python-format
msgid "Starting screenshot_process() (PID: %s)"
msgstr "Начиная screenshot_process () (PID: %s )"

#: gateone/applications/x11/app_x11.py:343
#, python-format
msgid "Terminating screenshot_process() (PID: %s)"
msgstr "Завершение screenshot_process () (PID: %s )"

#: gateone/applications/x11/app_x11.py:420
msgid "Run X11 applications."
msgstr "Запуск приложений X11."

#: gateone/applications/x11/app_x11.py:528
#, python-format
msgid "Active X11 Plugins: %s, "
msgstr "Активность X11 Плагины: %s , "

#: gateone/applications/x11/app_x11.py:1238
msgid ""
"Images are taking too long to process.  Forcing output settings to "
"safe/low overhead defaults."
msgstr "Изображения занимает слишком много времени на обработку. Принуждение настройки вывода в безопасные / низких накладных по умолчанию."

#: gateone/applications/x11/app_x11.py:1253
msgid "Resuming original output settings."
msgstr "Возобновление оригинальные настройки вывода."

#: gateone/applications/x11/app_x11.py:1299
msgid "Client bandiwdth: {0}/sec"
msgstr "Клиент bandiwdth: {0} / сек"

#: gateone/applications/x11/app_x11.py:1712
#, python-format
msgid "Could not connect to the X11 server (display %s)"
msgstr "Не могу подключиться к серверу X11 (дисплей %s )"

#: gateone/applications/x11/app_x11.py:1873
#, python-format
msgid "x11_command: %s"
msgstr "x11_command: %s"

#: gateone/applications/x11/app_x11.py:2147
#, python-format
msgid "Invalid display number given to full_refresh(): %s"
msgstr "Число Неверный дисплей уделено full_refresh (): %s"

#: gateone/applications/x11/app_x11.py:2310
msgid ""
"Error: Too too long waiting for the X11 display to start up.  Something "
"is wrong with the server."
msgstr "Ошибка: Слишком слишком долго ждал дисплей X11 пускать. Что-то не так с сервером."

#: gateone/applications/x11/app_x11.py:2323
#, python-format
msgid ""
"Error: The given display (%s) does not exist or you have not been granted"
" access to it."
msgstr "Ошибка: Данный дисплей ( %s ) не существует или вы не получили к нему доступ."

#: gateone/applications/x11/app_x11.py:2336
#, python-format
msgid "Application not configured: %s"
msgstr "Применение не настроен: %s"

#: gateone/applications/x11/app_x11.py:2441
msgid "// This is Gate One's X11 application settings file.\n"
msgstr "// Это X11 настройки приложения файл Gate One в. \ П"

#: gateone/applications/x11/app_x11.py:2453
#, python-format
msgid "%s not found.  Creating using template..."
msgstr "%s не найден. Создание с помощью шаблона ..."

#: gateone/applications/x11/app_x11.py:2459
#, python-format
msgid "%s created successfully."
msgstr "%s успешно создан."

#: gateone/applications/x11/app_x11.py:2461
#, python-format
msgid "Could not create xorg.conf (%s)"
msgstr "Не удалось создать xorg.conf ( %s )"

#: gateone/applications/x11/app_x11.py:2525
msgid "Path to docker command (if not just 'docker' in $PATH)."
msgstr "Путь к докер команду (если не просто «Докер» в $ PATH)."

#: gateone/applications/x11/app_x11.py:2531
msgid "Name of the docker image to create."
msgstr "Название Docker изображения, чтобы создать."

#: gateone/applications/x11/app_x11.py:2537
msgid "Name of the command (will show up in the application chooser)."
msgstr "Имя команды (будет отображаться в броузере приложений)."

#: gateone/applications/x11/app_x11.py:2543
msgid "Description of the command (help text for users)."
msgstr "Описание команды (помощь текста для пользователей)."

#: gateone/applications/x11/app_x11.py:2549
msgid ""
"Packages to install (if the command doesn't match the package name).  "
"Additional packages may also be given to install alongside the given "
"command inside the Docker container.  They will be installed via 'apt-get"
" install <packages>"
msgstr "Пакеты для установки (если команда не соответствует имени пакета). Дополнительные пакеты также могут быть даны, чтобы установить вместе с данной команды внутри контейнера Докер. Они будут установлены с помощью 'кв-получить установку <пакеты>"

#: gateone/applications/x11/app_x11.py:2557
msgid "ERROR: You must specify at least one application to install and configure."
msgstr "ОШИБКА: Вы должны указать хотя бы одно приложение по установке и настройке."

#: gateone/applications/x11/app_x11.py:2601
msgid "Adds X11 applications to Gate One."
msgstr "Добавляет приложения X11 в Gate One."

#: gateone/applications/x11/x11.py:1310
msgid "X11Display.resize(): Values must be given as integers."
msgstr "X11Display.resize (): Значения должны быть предоставлены в виде целых чисел."

#: gateone/applications/x11/x11.py:1572
#, python-format
msgid "Could not find keysym for key: %s"
msgstr "Не удалось найти символ клавиши для клавиши: %s"

#: gateone/applications/x11/x11.py:1573
msgid ""
"Please report what key you pressed and the above information in a ticket "
"here: https://github.com/liftoff/GateOne/issues (we'll make it work)"
msgstr "Пожалуйста, сообщите, какие ключевые Вы нажали и вышеуказанную информацию в билете здесь: https://github.com/liftoff/GateOne/issues (мы сделаем это работает)"

#: gateone/applications/x11/x11.py:1728 gateone/applications/x11/x11.py:1784
msgid "Could not load dbus module.  Screensaver inhibiting probably won't work."
msgstr "Не удалось загрузить DBus модуль. Заставка ингибирующий, вероятно, не будет работать."

#: gateone/applications/x11/x11.py:1776
msgid "Cannot re-enable a screensaver that was not disabled via this mechanism."
msgstr "Не можете повторно включить заставку, которая не была отключена с помощью этого механизма."

#: gateone/applications/x11/x11.py:2118
#, python-format
msgid ""
"frame_extents() takes a tuple (or list) of integers in the form of: "
"(left, right, top, bottom).  %s is not valid"
msgstr "frame_extents () принимает кортеж (или список) целых чисел в виде: (слева, справа, сверху, снизу). %s не действительна"

#: gateone/async/async.py:138
#, python-format
msgid "Exception in Future: %s (id: %s)"
msgstr "Исключение в будущее: %s (ID: %s )"

#: gateone/async/async.py:223
#, python-format
msgid "Shutting down %s"
msgstr "Выключение %s"

#: gateone/async/async.py:429
#, python-format
msgid "Starting the ThreadedRunner executor with %s worker threads."
msgstr "Запуск исполнителя ThreadedRunner с %s рабочих потоков."

#: gateone/async/async.py:480
#, python-format
msgid "Starting the MultiprocessRunner executor with %s worker processes."
msgstr "Запуск исполнителя MultiprocessRunner с %s рабочих процессов."

#: gateone/async/async.py:513
msgid "Shutting down the MultiprocessRunner executor."
msgstr "Выключение исполнителя MultiprocessRunner."

#: gateone/auth/authentication.py:158 gateone/auth/authentication.py:250
#: gateone/core/server.py:1987
#, python-format
msgid "Creating user directory: %s"
msgstr "Создание каталога пользователей: %s"

#: gateone/auth/authentication.py:162
msgid ""
"You're trying to use non-ASCII user information on a system that has the "
"locale set to ASCII (or similar).  Please changeyour system's locale to "
"something that supports Unicode characters. "
msgstr "Вы пытаетесь использовать информацию о пользователях, не-ASCII на системе, которая имеет языковым параметром ASCII (или аналогичный). Пожалуйста changeyour языковой системы к тому, что поддерживает символы Unicode. "

#: gateone/auth/authentication.py:365
msgid "Google auth failed"
msgstr "Google авт удалось"

#: gateone/auth/authentication.py:508
msgid "Kerberos auth failed"
msgstr "Kerberos аутентификации не удалось"

#: gateone/auth/authentication.py:509
#, python-format
msgid "KerberosAuthHandler user: %s"
msgstr "KerberosAuthHandler пользователь: %s"

#: gateone/auth/authentication.py:564
msgid "PAM auth failed"
msgstr "PAM аутентификации не удалось"

#: gateone/auth/authentication.py:568
#, python-format
msgid "PAMAuthHandler user: %s"
msgstr "Пользователь PAMAuthHandler: %s"

#: gateone/auth/authentication.py:590
msgid "CAS Server URL"
msgstr "CAS URL сервера"

#: gateone/auth/authentication.py:693
msgid "CAS authentication failed"
msgstr "Ошибка аутентификации CAS"

#: gateone/auth/authorization.py:116
#, python-format
msgid "{\"ip_address\": \"%s\"} %s -> %s failed requirement: %s"
msgstr "{\ "Ip_address \": \ " %s \ "} %s -> %s не удалось требование: %s"

#: gateone/auth/authorization.py:121
#, python-format
msgid "{\"ip_address\": \"%s\"} unknown user -> %s failed requirement: %s"
msgstr "{\ "Ip_address \": \ " %s \ "} неизвестный пользователь -> %s не удалось требование: %s"

#: gateone/auth/authorization.py:124
#, python-format
msgid "ERROR: %s"
msgstr "ОШИБКА: %s"

#: gateone/auth/authorization.py:148
msgid "Only valid users may access this function"
msgstr "Только действительные пользователи могут доступа к этой функции"

#: gateone/auth/authorization.py:169
msgid "You are not authorized to perform this action"
msgstr "Вы не авторизованы для выполнения этого действия"

#: gateone/auth/authorization.py:228
msgid "Your ability to perform this action has been restricted"
msgstr "Ваша способность выполнить это действие было ограничено"

#: gateone/auth/sso.py:132 gateone/auth/sso.py:133
msgid "Kerberos/GSSAPI Single Sign-On"
msgstr "Kerberos / GSSAPI Single Sign-On"

#: gateone/auth/sso.py:164 gateone/auth/sso.py:174
msgid "Kerberos Init failed"
msgstr "Kerberos Init удалось"

#: gateone/auth/sso.py:173
#, python-format
msgid "Kerberos Error: %s"
msgstr "Kerberos Ошибка: %s"

#: gateone/auth/sso.py:214
msgid "Headers have already been written"
msgstr "Заголовки уже написаны"

#: gateone/core/configuration.py:187
msgid ""
"GateOne supports many different CLI 'commands' which can be used to "
"invoke special functionality provided by plugins and applications (and "
"application's plugins).  Each command can have it's own options and most "
"will have a --help function of their own."
msgstr "GateOne поддерживает много различных 'команды' CLI которые могут быть использованы для вызова специальную функциональность, обеспечиваемую плагинов и приложений (и плагинов приложения). Каждая команда может иметь свой собственный варианты, и большинство будет иметь --help функцию самостоятельно."

#: gateone/core/configuration.py:296
msgid "Display version information."
msgstr "Показать информацию о версии."

#: gateone/core/configuration.py:301
msgid "DEPRECATED.  Use --settings_dir."
msgstr "Не рекомендуется. Используйте --settings_dir."

#: gateone/core/configuration.py:307
msgid "Path to the settings directory."
msgstr "Путь к каталогу настроек."

#: gateone/core/configuration.py:314
msgid ""
"Path where Gate One should store temporary global files (e.g. rendered "
"templates, CSS, JS, etc)."
msgstr "Путь, где Gate One должен хранить временные глобальные файлы (например, оказываемых шаблоны, CSS, JS, и т.д.)."

#: gateone/core/configuration.py:323
msgid "Enable debugging features such as auto-restarting when files are modified."
msgstr "Включить отладку функции, такие как авто-перезапуска, когда файлы были изменены."

#: gateone/core/configuration.py:329
msgid "Use the given 45-character string for cookie encryption."
msgstr "Использовать данный 45-символьная строка для шифрования печенья."

#: gateone/core/configuration.py:335
msgid "DEPRECATED: Use the 'commands' option in the terminal settings."
msgstr "Рекомендуется к использованию: Используйте опцию 'команды' в настройках терминала."

#: gateone/core/configuration.py:342
msgid ""
"Run on the given address.  Default is all addresses (IPv6 included).  "
"Multiple address can be specified using a semicolon as a separator (e.g. "
"'127.0.0.1;::1;10.1.1.100')."
msgstr "Запустить на указанный адрес. По умолчанию все адреса (включая IPv6). Несколько адрес может быть определен с запятой в качестве разделителя (например "127.0.0.1; :: 1; 10.1.1.100 ')."

#: gateone/core/configuration.py:349
msgid "Run on the given port."
msgstr "Запустите на данном порту."

#: gateone/core/configuration.py:355
msgid "Enable Unix socket support."
msgstr "Включить поддержку сокета Unix."

#: gateone/core/configuration.py:361
msgid "Path to the Unix socket (if --enable_unix_socket=True)."
msgstr "Путь к разъему Unix (если --enable_unix_socket = True)."

#: gateone/core/configuration.py:368
msgid "If enabled Gate One will run without SSL (generally not a good idea)."
msgstr "Если включен Gate One будет работать без SSL (обычно не хорошая идея)."

#: gateone/core/configuration.py:375
msgid "Path to the SSL certificate.  Will be auto-generated if not found."
msgstr "Путь к сертификату SSL. Будет автоматически сгенерированный если не найден."

#: gateone/core/configuration.py:384
msgid "Path to the SSL keyfile.  Will be auto-generated if none is provided."
msgstr "Путь к SSL файл_ключа. Будет автоматически сгенерированный если ни один не предоставляется."

#: gateone/core/configuration.py:392
msgid ""
"Path to a file containing any number of concatenated CA certificates in "
"PEM format.  They will be used to authenticate clients if the 'ssl_auth' "
"option is set to 'optional' or 'required'."
msgstr "Путь к файлу, содержащему любое количество сцепленных сертификатов ЦС в формате PEM. Они будут использоваться для проверки подлинности клиентов, если опция 'ssl_auth' установлен в 'опция' или 'требуется'."

#: gateone/core/configuration.py:402
msgid ""
"Enable the use of client SSL (X.509) certificates as a secondary "
"authentication factor (the configured 'auth' type will come after SSL "
"auth).  May be one of 'none', 'optional', or 'required'.  NOTE: Only "
"works if the 'ca_certs' option is configured."
msgstr "Разрешить использование клиентского SSL (X.509) сертификатов в качестве вторичного фактора аутентификации (заданный тип 'авт' придет после SSL авт). Может быть одним из 'никто', 'опция', или 'необходимого'. ПРИМЕЧАНИЕ: Работает только если параметр "ca_certs" настроен."

#: gateone/core/configuration.py:413
msgid "Path to the location where user files will be stored."
msgstr "Путь к месту, где пользовательские файлы будут храниться."

#: gateone/core/configuration.py:420
msgid ""
"Maximum length of time to keep any given user log before it is "
"automatically removed."
msgstr "Максимальная длина времени, чтобы держать любую заданную журнал пользователя, прежде чем она автоматически удаляется."

#: gateone/core/configuration.py:429
msgid "Path to the location where session information will be stored."
msgstr "Путь к месту, где будет храниться информация о сессии."

#: gateone/core/configuration.py:439
#, python-format
msgid ""
"Syslog facility to use when logging to syslog (if syslog_session_logging "
"is enabled).  Must be one of: %s., "
msgstr "Syslog объект будут использоваться при регистрации в системном журнале (если syslog_session_logging включена). Должен быть один из: %s ., "

#: gateone/core/configuration.py:446
msgid ""
"Amount of time that a session is allowed to idle before it is killed.  "
"Accepts <num>X where X could be one of s, m, h, or d for seconds, "
"minutes, hours, and days.  Set to '0' to disable the ability to resume "
"sessions."
msgstr "Количество времени, что сессия допускается работать на холостом ходу, прежде чем он будет убит. Принимает <число> X, где X может быть одним из S, M, ч, или D для секунд, минут, часов и дней. Установите в "0", чтобы отключить возможность возобновить занятия."

#: gateone/core/configuration.py:456
msgid ""
"Generate a new API key that an external application can use to embed Gate"
" One."
msgstr "Создайте новый ключ API, что внешние приложения могут использовать для встраивания Gate One."

#: gateone/core/configuration.py:463
#, python-format
msgid "Authentication method to use.  Valid options are: %s"
msgstr "Используемый способ проверки подлинности. Правильные опции: %s"

#: gateone/core/configuration.py:474
msgid "How long before an API authentication object becomes invalid."
msgstr "Как долго, прежде чем объект аутентификации API становится недействительным."

#: gateone/core/configuration.py:482
msgid ""
"Kerberos REALM (aka DOMAIN) to use when authenticating clients.  Only "
"relevant if Kerberos authentication is enabled."
msgstr "Kerberos ОБЛАСТЬ (ака ДОМЕН) для использования при аутентификации клиентов. Только актуальным, если аутентификация Kerberos включен."

#: gateone/core/configuration.py:490
msgid ""
"Kerberos service (aka application) to use.  Only relevant if Kerberos "
"authentication is enabled."
msgstr "Служба Kerberos (ака приложение) использовать. Только актуальным, если аутентификация Kerberos включен."

#: gateone/core/configuration.py:498
msgid ""
"Basic auth REALM to display when authenticating clients.  Default: "
"hostname.  Only relevant if PAM authentication is enabled."
msgstr "Основные авт REALM для отображения при аутентификации клиентов. По умолчанию: имя хоста. Только актуальным, если аутентификация PAM включен."

#: gateone/core/configuration.py:509
msgid ""
"PAM service to use.  Defaults to 'login'. Only relevant if PAM "
"authentication is enabled."
msgstr "Службы PAM для использования. По умолчанию 'логин'. Только актуальным, если аутентификация PAM включен."

#: gateone/core/configuration.py:517
msgid ""
"When embedding Gate One this option is available to plugins, "
"applications, and templates so they know they're running in embedded mode"
" and can change behavior (if necessary)."
msgstr "При внедрении Gate One эта опция доступна для плагинов, приложений и шаблоны, чтобы они знали, что они работают в интегрированном режиме и может изменить поведение (в случае необходимости)."

#: gateone/core/configuration.py:529
#, python-format
msgid ""
"The locale (e.g. pt_PT) Gate One should use for translations.  If not "
"provided, will default to $LANG (which is '%s' in your current shell)."
msgstr "Место действия (например pt_PT) Gate One должны использовать для переводов. Если не предусмотрено, по умолчанию будет $ LANG (что ' %s 'в текущей оболочке)."

#: gateone/core/configuration.py:535
msgid ""
"A JavaScript object (string) that will be used when running "
"GateOne.init() inside index.html.  Example: --js_init=\"{theme: "
"'white'}\" would result in GateOne.init({theme: 'white'})"
msgstr "Объект JavaScript (строка), который будет использоваться при запуске GateOne.init () внутри index.html. Пример: --js_init = \ "{тема: 'белый'} \" приведет к GateOne.init ({тема: 'белый'})"

#: gateone/core/configuration.py:545
msgid ""
"If enabled a separate listener will be started on port 80 that redirects "
"users to the configured port using HTTPS."
msgstr "Если включен отдельный слушатель будет запущен на порту 80, который перенаправляет пользователей на заданный порт, используя HTTPS."

#: gateone/core/configuration.py:552
msgid ""
"An optional prefix to place before all Gate One URLs. e.g. '/gateone/'.  "
"Use this if Gate One will be running behind a reverse proxy where you "
"want it to be located at some sub-URL path."
msgstr "Необязательный префикс разместить до всех Gate One URL. например, '/ gateone /'. Используйте это, если Gate One будет работать за обратным прокси, где вы хотите, чтобы он был расположен на некотором суб-URL пути."

#: gateone/core/configuration.py:562
msgid ""
"A semicolon-separated list of origins you wish to allow access to your "
"Gate One server over the WebSocket.  This value may contain "
"hostnames/FQDNs (e.g. foo;foo.bar;) and IP addresses.  This value must "
"contain all the hostnames/IPs that users will use to connect to Gate One."
"  Alternatively, '*' may be  specified to allow access from anywhere.  "
"NOTE: Using a '*' is only a good idea if you've configured Gate One to "
"use API authentication."
msgstr "Разделенных точкой с запятой список происхождении вы хотите разрешить доступ к вашему Gate One сервер по WebSocket. Это значение может содержать имена хостов / FQDNs (например Foo; foo.bar;) и IP-адреса. Это значение должно содержать все имена хостов / IP-адресов, что пользователи будут использовать для подключения к Gate One. Кроме того, '*' может быть указан, чтобы разрешить доступ из любой точки. ПРИМЕЧАНИЕ: Использование '*' только хорошая идея, если вы настроили Gate One для использования проверки подлинности API."

#: gateone/core/configuration.py:576
msgid "Define the path to the pid file."
msgstr "Определите путь к файлу PID."

#: gateone/core/configuration.py:583
msgid "Drop privileges and run Gate One as this user/uid."
msgstr "Бросьте привилегии и запустить Gate One, как этого пользователя / жидкости."

#: gateone/core/configuration.py:590
msgid "Drop privileges and run Gate One as this group/gid."
msgstr "Бросьте привилегии и запустить Gate One, как этой группы / GID."

#: gateone/core/configuration.py:597
msgid ""
"The 'key:secret,...' API key pairs you wish to use (only applies if using"
" API authentication)"
msgstr "'Ключ: секрет, ...' API ключ пары вы хотите использовать (применяется только при использовании аутентификации API)"

#: gateone/core/configuration.py:605
msgid ""
"Combines all of Gate One's JavaScript files into one big file and saves "
"it to the given path (e.g. ./gateone.py --combine_js=/tmp/gateone.js)"
msgstr "Объединяет все файлы Gate One в JavaScript в один большой файл и сохраняет его в заданный путь (например ./gateone.py --combine_js = / TMP / gateone.js)"

#: gateone/core/configuration.py:615
msgid ""
"Combines all of Gate One's CSS Template files into one big file and saves"
" it to the given path (e.g. ./gateone.py --combine_css=/tmp/gateone.css)."
msgstr "Объединяет все файлы CSS шаблонов Gate One в в один большой файл и сохраняет его в заданный путь (например ./gateone.py --combine_css = / TMP / gateone.css)."

#: gateone/core/configuration.py:625
msgid ""
"Use this setting in conjunction with --combine_css if the <div> where "
"Gate One lives is named something other than #gateone"
msgstr "Используйте этот параметр в сочетании с --combine_css если <дел>, где Gate One живет называется иначе, чем #gateone"

#: gateone/core/configuration.py:634
msgid ""
"The number of processes to spawn use when using multiprocessing. Default "
"is: <number of cores> + 1.  Set to 0 to disable multiprocessing."
msgstr "Количество процессов на нерест использование при использовании многопроцессорной. По умолчанию: <количество ядер> + 1 Набор в 0 для отключения многопроцессорной."

#: gateone/core/configuration.py:644
msgid ""
"Only configure Gate One (create SSL certs, conf.d, etc).  Do not start "
"any Gate One processes."
msgstr "Только настроить Gate One (создать SSL сертификаты, conf.d и т.д.). Не начинайте какие ворота Один процессы."

#: gateone/core/configuration.py:704
msgid ""
"Gate One settings are incomplete.  A new <settings_dir>/10server.conf "
"will be generated."
msgstr "Gate One настройки являются неполными. Новый <settings_dir> /10server.conf будет."

#: gateone/core/configuration.py:712
msgid ""
"You have a 10server.conf but it is either invalid (syntax error) or "
"missing essential settings."
msgstr "У вас есть 10server.conf но это либо недействительным (ошибка синтаксиса) или недостающих основных параметров."

#: gateone/core/configuration.py:818
#, python-format
msgid ""
"Old server.conf file found.  Converting to the new format as %s, %s, and "
"%s"
msgstr "Старый server.conf найденный файл. Преобразование в новый формат, как %s , %s , и %s"

#: gateone/core/configuration.py:861 gateone/core/server.py:4269
msgid ""
"// This file contains the key and secret pairs used by Gate One's API "
"authentication method.\n"
msgstr "// Этот файл содержит ключ и тайные пары используемый метод аутентификации API Gate One в. \ П"

#: gateone/core/configuration.py:873
msgid "// This is Gate One's main settings file.\n"
msgstr "// Это основной файл настройки Gate One в. \ П"

#: gateone/core/configuration.py:879
msgid "// This is Gate One's authentication settings file.\n"
msgstr "// Это файл настройки идентификации Gate One в. \ П"

#: gateone/core/configuration.py:973
#, python-format
msgid "%s does not exist"
msgstr "%s не существует"

#: gateone/core/configuration.py:1005
msgid " <-- Something went wrong right here (or right above it)"
msgstr " <- То пошло не так прямо здесь (или прямо над ним)"

#: gateone/core/configuration.py:1013
msgid ""
"Got an exception trying to display precisely where the problem was.  This"
" usually happens when you've used single quotes (') instead of double "
"quotes (\")."
msgstr "Получил исключение пытается отобразить именно там, где проблема была. Это обычно происходит, когда вы использовали одинарные кавычки (') вместо двойных кавычек (\ ")."

#: gateone/core/configuration.py:1321
#, python-format
msgid "Non-theme CSS has been combined and saved to: %s"
msgstr "Номера для темы CSS была объединена и сохранены в: %s"

#: gateone/core/configuration.py:1337
#, python-format
msgid "The %s theme CSS has been combined and saved to: %s"
msgstr "В %s тема CSS была объединена и сохранены в: %s"

#: gateone/core/server.py:493
#, python-format
msgid "Removing log due to age (>%s old): %s"
msgstr "Удаление журнала в связи с возрастом (> %s старый): %s"

#: gateone/core/server.py:537
#, python-format
msgid "Removing old session files due to age (>%s old): %s"
msgstr "Удаление старых файлов сессий в связи с возрастом (> %s старый): %s"

#: gateone/core/server.py:559
#, python-format
msgid "You do not have permission to send messages to %s."
msgstr "Вы не имеете разрешения для отправки сообщений %s ."

#: gateone/core/server.py:579
msgid "You do not have permission to broadcast messages."
msgstr "Вы не имеете разрешения на трансляцию сообщения."

#: gateone/core/server.py:590
msgid "You do not have permission to list connected users."
msgstr "Вы не должны прав для вывода подключенных пользователей."

#: gateone/core/server.py:632
msgid "Killing all sessions..."
msgstr "Погибли все сеансы ..."

#: gateone/core/server.py:677
msgid "All user sessions have terminated."
msgstr "Все пользовательские сеансы кончились."

#: gateone/core/server.py:693
msgid "{session} timeout."
msgstr "{Сессия} таймаут."

#: gateone/core/server.py:701
msgid "Exception encountered in timeout_sessions(): {exception}"
msgstr "Исключение встречается в timeout_sessions (): {} Исключение"

#: gateone/core/server.py:725
#, python-format
msgid "Broadcasting %s to all users"
msgstr "Радиовещание %s для всех пользователей"

#: gateone/core/server.py:901
msgid "DownloadHandler: Could not determine use session"
msgstr "DownloadHandler: Не удалось определить использование сессии"

#: gateone/core/server.py:1245
msgid "{path} has been removed.  Removing from file checker."
msgstr "{Путь} был удален. Удаление из файла проверки."

#: gateone/core/server.py:1258
msgid ""
"Exception encountered trying to execute the file update function for "
"{path}..."
msgstr "Исключение столкнулись попытке выполнить функцию обновления файла для {PATH} ..."

#: gateone/core/server.py:1289
#, python-format
msgid "Settings have been modified.  Reloading from %s"
msgstr "Настройки были изменены. Перегруз из %s"

#: gateone/core/server.py:1296
msgid "Settings have NOT been loaded."
msgstr "Параметры не были загружены."

#: gateone/core/server.py:1354
#, python-format
msgid "(Broadcast) %s"
msgstr "(Трансляция) %s"

#: gateone/core/server.py:1587
#, python-format
msgid "{\"ip_address\": \"%s\"} Access Denied (blacklisted)."
msgstr "{\ "Ip_address \": \ " %s \ "} Access Denied (черный список)."

#: gateone/core/server.py:1590
#, python-format
msgid "Your IP address (%s) has been blacklisted"
msgstr "Ваш IP-адрес ( %s ) занесен в черный список"

#: gateone/core/server.py:1602
#, python-format
msgid "WebSocket opened (%s %s) via origin %s."
msgstr "WebSocket открыл ( %s %s ) с помощью происхождения %s ."

#: gateone/core/server.py:1606
#, python-format
msgid "{\"ip_address\": \"%s\"} WebSocket opened (unknown user)."
msgstr "{\ "Ip_address \": \ " %s \ "} WebSocket открыл (неизвестный пользователь)."

#: gateone/core/server.py:1617
#, python-format
msgid "{\"ip_address\": \"%s\"} Unauthenticated WebSocket attempt."
msgstr "{\ "Ip_address \": \ " %s \ "} Unauthenticated попытка WebSocket."

#: gateone/core/server.py:1679
msgid "Message rejected due to invalid origin."
msgstr "Сообщение отклонено вследствие неверного происхождения."

#: gateone/core/server.py:1685
msgid "'Error: Message bust be a JSON dict.'"
msgstr "'Ошибка: Сообщение бюст быть JSON Dict."

#: gateone/core/server.py:1688
msgid "'Error: We only accept JSON here.'"
msgstr "'Ошибка: Мы только принимаем JSON здесь.'"

#: gateone/core/server.py:1704
#, python-format
msgid "Error in WebSocket action, %s: %s (%s line %s)"
msgstr "Ошибка в WebSocket действия, %s : %s ( %s линия %s )"

#: gateone/core/server.py:1710
#, python-format
msgid "Client sent unknown WebSocket action: %s"
msgstr "Клиент послал неизвестный действия WebSocket: %s"

#: gateone/core/server.py:1734
#, python-format
msgid "WebSocket closed (%s %s)."
msgstr "WebSocket закрыты ( %s %s )."

#: gateone/core/server.py:1736
msgid "WebSocket closed (unknown user)."
msgstr "WebSocket закрыты (Неизвестный пользователь)."

#: gateone/core/server.py:1765
msgid "WebSocket Latency: {0}ms"
msgstr "WebSocket Задержка: {0} мс"

#: gateone/core/server.py:1883
msgid "API AUTH: Invalid API authentication object (missing api_key)."
msgstr "API AUTH: Неправильный объект аутентификации API (отсутствует api_key)."

#: gateone/core/server.py:1901 gateone/core/server.py:3782
#, python-format
msgid "API AUTH: Unsupported API auth signature method: %s"
msgstr "API AUTH: метод API авторизации подпись поддерживается: %s"

#: gateone/core/server.py:1908 gateone/core/server.py:3787
#, python-format
msgid "API AUTH: Unsupported API version: %s"
msgstr "API AUTH: поддерживается версия API: %s"

#: gateone/core/server.py:1914
msgid "API AUTH: API Key not found."
msgstr "API AUTH: ключ API не найдено."

#: gateone/core/server.py:1923
msgid "API AUTH: Signature check failed."
msgstr "API AUTH: проверка подписи не удалось."

#: gateone/core/server.py:1924
msgid "Got signature: {0}, expected: {1}"
msgstr "Получил подпись: {0} , ожидается: {1}"

#: gateone/core/server.py:1935
#, python-format
msgid "API AUTH: replay attack detected!  User: %s, Remote IP: %s, Origin: %s"
msgstr "API AUTH: обнаружена атака воспроизведения! Пользователь: %s , Remote IP: %s , Происхождение: %s"

#: gateone/core/server.py:1937
msgid "API AUTH: Replay attack detected!  This event has been logged."
msgstr "API AUTH: обнаружен Повтор нападение! Это событие было зарегистрировано."

#: gateone/core/server.py:1946
msgid ""
"API AUTH: Authentication failed due to an expired auth object.  If you "
"just restarted the server this is normal (users just need to reload the "
"page).  If  this problem persists it could be a problem with the server's"
" clock (either this server or the server(s) embedding Gate One)."
msgstr "API AUTH: Ошибка аутентификации вследствие истекшим объекта авт. Если вы только что перезапустили сервер это нормально (пользователи просто нужно перезагрузить страницу). Если проблема не устраняется, это может быть проблема с часами сервера (либо сервера или сервера (ов) вложения Gate One)."

#: gateone/core/server.py:1954
msgid ""
"AUTH FAILED: Authentication object timed out. Try reloading this page "
"(F5)."
msgstr "Ошибка аутентификации: Объект аутентификации истекло. Попробуйте перезагрузки эту страницу (F5)."

#: gateone/core/server.py:1958
msgid ""
"AUTH FAILED: If the problem persists after reloading this page please "
"contact your server administrator to notify them of the issue."
msgstr "Ошибка аутентификации: Если проблема не устраняется после перезагрузки эту страницу, пожалуйста, обратитесь к администратору сервера, чтобы уведомить их о проблеме."

#: gateone/core/server.py:1964
msgid "API Authentication Successful"
msgstr "Аутентификация API Успешная"

#: gateone/core/server.py:2055
msgid "Proxy in use: Client URL differs from server."
msgstr "Прокси в использование: Client URL отличается от сервера."

#: gateone/core/server.py:2078 gateone/core/server.py:2085
msgid "Unauthenticated WebSocket attempt."
msgstr "Unauthenticated WebSocket попытка."

#: gateone/core/server.py:2125
msgid ""
"Client tried to use API-based authentication but this server is "
"configured with 'auth = \"{0}\"'.  Did you forget to set '\"auth\": "
"\"api\"' in the settings?"
msgstr "Клиент попытался использовать аутентификацию API на основе, но это сервер настроен с 'авт = \ " {0} \ "'. Вы забыли установить '\ "авт \": \ "API \"' в настройках?"

#: gateone/core/server.py:2130
msgid ""
"AUTHENTICATION ERROR: Server is not configured to perform API-based "
"authentication.  Did someone forget to set '\"auth\": \"api\"' in the "
"settings?"
msgstr "АУТЕНТИФИКАЦИЯ ОШИБКА: Сервер не настроен для выполнения аутентификации API на основе. Кто-то забудьте установить '\ "авт \": \ "API \"' в настройках?"

#: gateone/core/server.py:2158
msgid "Authentication failed for unknown user"
msgstr "Ошибка аутентификации для неизвестного пользователя"

#: gateone/core/server.py:2159
msgid "AUTHENTICATION ERROR: User unknown"
msgstr "АУТЕНТИФИКАЦИЯ ОШИБКА: неизвестный Пользователь"

#: gateone/core/server.py:2179
msgid ""
"User {upn} authenticated successfully via origin {origin} (location: "
"{location})."
msgstr "Пользователь {сор} успешной аутентификации через происхождения {происхождения} (место нахождения: {расположение})."

#: gateone/core/server.py:2192
msgid "Please wait while the server is restarted..."
msgstr "Пожалуйста, подождите, пока сервер перезапускается ..."

#: gateone/core/server.py:2233
msgid "Licensed user limit {max_users} exceeded: {user_count} connected users"
msgstr "Лицензия пользователь предел {MAX_USERS} превысил: {user_count} подключенные пользователи"

#: gateone/core/server.py:2619
msgid "Modification to theme file detected.  Theme will be recreated."
msgstr "Модификация с тематическим файл обнаружен. Тема будет воссоздан."

#: gateone/core/server.py:2727
#, python-format
msgid "No expired %s files at client %s"
msgstr "Нет просроченные %s файлов на клиентском %s"

#: gateone/core/server.py:2730
#, python-format
msgid "Requesting deletion of expired files at client %s: %s"
msgstr "Запрос удаления устаревших файлов на клиентском %s : %s"

#: gateone/core/server.py:2786
msgid "File Request Error: File not found ({0})"
msgstr "Запрос файла Ошибка: Файл не найден ( {0} )"

#: gateone/core/server.py:2899 gateone/core/server.py:3201
msgid "send_js is false; will not send JavaScript."
msgstr "send_js ложно; не будет посылать JavaScript."

#: gateone/core/server.py:2908 gateone/core/server.py:3131
msgid "send_css is false; will not send CSS."
msgstr "send_css ложно; не будет посылать CSS."

#: gateone/core/server.py:2977
#, python-format
msgid "send_js_or_css(): File not found: %s"
msgstr "send_js_or_css (): Файл не найден: %s"

#: gateone/core/server.py:3062 gateone/core/server.py:3136
msgid "File does not exist: {0}"
msgstr "Файл не существует: {0}"

#: gateone/core/server.py:3297
#, python-format
msgid "Translation file, %s could not be found"
msgstr "Файл Перевод, %s не может быть найден"

#: gateone/core/server.py:3322
msgid "Error: No message to send."
msgstr "Ошибка: никакое сообщение для отправки."

#: gateone/core/server.py:3325
msgid "Error: Missing UPN."
msgstr "Ошибка: Отсутствует имя участника."

#: gateone/core/server.py:3329
msgid "User Message: {0}"
msgstr "Сообщение пользователя: {0}"

#: gateone/core/server.py:3589
msgid ""
"In order to use Google authentication you must create a Google project "
"for your installation and add:\n"
"\t{\"google_oauth\": {\"key\": \"<YOUR CLIENT ID>\", \"secret\": \"<YOUR "
"CLIENT SECRET>\"}} to your 20authentication.conf (under the \"gateone\" "
"section)."
msgstr "Для того чтобы использовать аутентификацию Google необходимо создать проект Google для установки и добавить: \ п \ т {\ "google_oauth \": {\ "ключ \": \ "<ВАШ КЛИЕНТ ID> \", \ "Секрет \ ": \" <ВАШ КЛИЕНТ SECRET> \ "}} на свой 20authentication.conf (под \" gateone раздел \ ")."

#: gateone/core/server.py:3595
msgid ""
"To create a Google auth client ID and secret go to: "
"https://console.developers.google.com/ and click on \"APIs and Auth\".  "
"Then click \"Create New Client ID\". Set the \"JavaScript Origins\" value"
" to your Gate One server's address and the \"Redirect URIs\" to "
"https://<your Gate One server FQDN>/auth"
msgstr "Для создания клиентской аутентификации Google ID и секретный Перейти к: https://console.developers.google.com/ и нажмите на \ "API, и Auth \". Затем нажмите \ "Создать Client ID \". В списке \ "JavaScript Origins \" значение к адресу вашего Gate One сервера и \ "перенаправление URI, \" чтобы HTTPS: // <ваш Gate One сервер полное доменное имя> / аутентификации"

#: gateone/core/server.py:3602
msgid ""
"For example, if your \"JavaScript Origins\" is: "
"https://gateone.example.com/"
msgstr "Например, если ваш \ "JavaScript Origins \" является: https://gateone.example.com/"

#: gateone/core/server.py:3605
msgid "Your \"Redirect URIs\" would be: https://gateone.example.com/auth"
msgstr "Ваш \ "перенаправление URI, \" будет: https://gateone.example.com/auth"

#: gateone/core/server.py:3615
#, python-format
msgid "Using %s authentication"
msgstr "Использование %s аутентификацию"

#: gateone/core/server.py:3617
msgid "No authentication method configured. All users will be ANONYMOUS"
msgstr "Ни один метод аутентификации не настроен. Все пользователи будут анонимными"

#: gateone/core/server.py:3709
#, python-format
msgid "Loaded global plugins: %s"
msgstr "Загруженные глобальные плагины: %s"

#: gateone/core/server.py:3730
msgid ""
"\n"
"[1;31mAPI Authentication Failed![0m"
msgstr "\ П [1; 31mAPI Ошибка аутентификации! [0m"

#: gateone/core/server.py:3731
#, python-format
msgid "Checking: %s"
msgstr "Проверка: %s"

#: gateone/core/server.py:3736
#, python-format
msgid "Not valid JSON: %s"
msgstr "Не доступно JSON: %s"

#: gateone/core/server.py:3750
#, python-format
msgid "You appear to be missing the following keys from your JSON object: %s"
msgstr "Вы, кажется, не быть следующие разделы вашего объекта JSON: %s"

#: gateone/core/server.py:3755
msgid "You don't appear to have any API keys configured."
msgstr "Вы, кажется, не имеют никаких ключей API настроенные."

#: gateone/core/server.py:3756
msgid "Tip: You can create them on-demand via: gateone --new_api_key"
msgstr "Совет: Вы можете создавать их по требованию с помощью: gateone --new_api_key"

#: gateone/core/server.py:3765
#, python-format
msgid "The given API key (%s) was not found."
msgstr "Данный ключ API ( %s ) не был найден."

#: gateone/core/server.py:3769
#, python-format
msgid "The given API key (%s) has no secret!"
msgstr "Данный API ключ ( %s ) не имеет никакого секрета!"

#: gateone/core/server.py:3770
msgid "Your api_keys setting is probably not in the correct format."
msgstr "Ваша установка api_keys, вероятно, не в правильном формате."

#: gateone/core/server.py:3771
msgid "The correct format is {\"api_keys\": {\"<API key>\":\"<secret>\"}}"
msgstr "Правильный формат является {\ "api_keys \": {\ "<ключ API> \": \ "<секрет> \"}}"

#: gateone/core/server.py:3772
msgid ""
"It is recommended that you run 'gateone --new_api_key' and modify (or at "
"least look at) the resulting 30api_keys.conf"
msgstr "Рекомендуется запуске 'gateone --new_api_key' и изменить (или по крайней мере посмотреть на) в результате 30api_keys.conf"

#: gateone/core/server.py:3794
#, python-format
msgid ""
"The generated signature (%s) does not match what was provided in the "
"given auth object (%s)"
msgstr "Сформированный подпись ( %s ) не соответствует тому, что было предусмотрено в данном Идент объекта ( %s )"

#: gateone/core/server.py:3816
msgid ""
"A license file is already installed.  Are you sure you want to replace "
"it? (y/n) "
msgstr "Файл лицензии уже установлена. Вы уверены, что хотите заменить его? (Да / нет) "

#: gateone/core/server.py:3858
msgid ""
"Could not import pyelliptic which is required to validate licenses.  "
"Please install it:  sudo pip install pyelliptic"
msgstr "Не удалось импортировать pyelliptic который необходим для проверки лицензии. Пожалуйста, установите его: Суда пункт установить pyelliptic"

#: gateone/core/server.py:3861
msgid "Or you could just download it: https://github.com/yann2192/pyelliptic"
msgstr "Или вы можете просто скачать его: https://github.com/yann2192/pyelliptic"

#: gateone/core/server.py:3884
msgid "License for '{product}' has expired: {license}"
msgstr "Лицензия на '{продукта}' истек: {лицензия}"

#: gateone/core/server.py:3890
#, python-format
msgid "License has an invalid signature: %s"
msgstr "Лицензия имеет неверную подпись: %s"

#: gateone/core/server.py:3895
msgid "License for '{product}' will expire in less than 30 days: {license}"
msgstr "Лицензия на '{продукта}' истекает менее чем за 30 дней: {лицензия}"

#: gateone/core/server.py:3923
#, python-format
msgid "Could not find/create settings directory at %s"
msgstr "Не удалось найти / создать каталог настроек в %s"

#: gateone/core/server.py:3935
msgid "Broadcast messages to users connected to Gate One."
msgstr "Широковещательные сообщения для пользователей, подключенных к Gate One."

#: gateone/core/server.py:3939
msgid "Install a commercial license for Gate One."
msgstr "Установите коммерческую лицензию для Gate One."

#: gateone/core/server.py:3943
msgid "Test API authentication by validating a JSON auth object."
msgstr "Тест аутентификации API путем проверки объекта JSON аутентификации."

#: gateone/core/server.py:3947
msgid ""
"You probably want to provide a different destination via "
"--log_file_prefix=/path/to/gateone.log"
msgstr "Вы, наверное, хотите, чтобы обеспечить другие пункты назначения через --log_file_prefix = / путь / к / gateone.log"

#: gateone/core/server.py:3969 gateone/core/server.py:3977
#, python-format
msgid "Could not create log directory: %s"
msgstr "Не удалось создать каталог журнала: %s"

#: gateone/core/server.py:4006
#, python-format
msgid "Could not write to the log: %s"
msgstr "Не удалось записать в журнал: %s"

#: gateone/core/server.py:4123
#, python-format
msgid "Unknown CLI command: '%s'"
msgstr "Неизвестный CLI команда: ' %s '"

#: gateone/core/server.py:4139
msgid "Imported applications: {0}"
msgstr "Импортные приложения: {0}"

#: gateone/core/server.py:4149
msgid "The configured 'uid' ({0}) does not exist."
msgstr "Настроен 'UID' ( {0} ) не существует."

#: gateone/core/server.py:4160
msgid "The configured 'gid' ({0}) does not exist."
msgstr "Сконфигурированных 'GID' ( {0} ) не существует."

#: gateone/core/server.py:4165
msgid "Running as non-root; will not drop privileges."
msgstr "Выполнение не-корня; не упадет привилегии."

#: gateone/core/server.py:4179
#, python-format
msgid ""
"Gate One could not create %s.  Please ensure that user, %s has permission"
" to create this directory or create it yourself and make user, %s its "
"owner."
msgstr "Gate One не может создать %s . Пожалуйста, убедитесь, что пользователь, %s имеет разрешение на создание этого каталога или создать его самостоятельно и сделать пользователю, %s своего владельца."

#: gateone/core/server.py:4190
#, python-format
msgid "Failed to recursively change permissions of user_dir: %s, uid: %s, gid: %s"
msgstr "Не удалось рекурсивно изменить права user_dir: %s , UID: %s , GID: %s"

#: gateone/core/server.py:4203
#, python-format
msgid ""
"Error: Gate One could not create %s.  Please ensure that user, %s has "
"permission to create this directory or create it yourself and make user, "
"%s its owner."
msgstr "Ошибка: Gate One не может создать %s . Пожалуйста, убедитесь, что пользователь, %s имеет разрешение на создание этого каталога или создать его самостоятельно и сделать пользователю, %s своего владельца."

#: gateone/core/server.py:4228
#, python-format
msgid "[1;31mERROR:[0m Could not create %s for log_file_prefix: %s"
msgstr "[1; 31mERROR: [0m Не удалось создать %s для log_file_prefix: %s"

#: gateone/core/server.py:4230
msgid ""
"You probably want to change this option, run Gate One as root, or create "
"that directory and give the proper user ownership of it."
msgstr "Вы, наверное, хотите, чтобы изменить этот параметр, запустите Gate One, как корень, или создайте эту директорию и дать надлежащую владельца-пользователя него."

#: gateone/core/server.py:4274
#, python-format
msgid "A new API key has been generated: %s"
msgstr "Новый ключ API, был сформирован: %s"

#: gateone/core/server.py:4275
msgid "This key can now be used to embed Gate One into other applications."
msgstr "Этот ключ теперь можно использовать для встраивания Gate One в другие приложения."

#: gateone/core/server.py:4291
#, python-format
msgid "Version: %s (%s)"
msgstr "Версия: %s ( %s )"

#: gateone/core/server.py:4292
#, python-format
msgid "Tornado version %s"
msgstr "Торнадо версия %s"

#: gateone/core/server.py:4310
#, python-format
msgid ""
"Connections to this server will be allowed from the following origins: "
"'%s'"
msgstr "Подсоединение к данному серверу будет разрешено из следующих источников: ' %s '"

#: gateone/core/server.py:4327
msgid ""
"Gate One could not create {ssl_base} ({e}). Are you using the correct "
"--settings_dir?"
msgstr "Gate One не может создать {ssl_base} ({е}). Используете ли вы правильный --settings_dir?"

#: gateone/core/server.py:4331
msgid "No SSL private key found.  One will be generated."
msgstr "Нет закрытый ключ SSL не найдено. Один будет."

#: gateone/core/server.py:4335
msgid "No SSL certificate found.  One will be generated."
msgstr "Нет удостоверения SSL не найдено. Один будет."

#: gateone/core/server.py:4340
msgid ""
"Logging is set to DEBUG.  Be aware that this will record the keystrokes "
"of all users.  Don't be evil!"
msgstr "Вход установлен в DEBUG. Знайте, что это будет записывать нажатия клавиш всех пользователей. Не будь злым!"

#: gateone/core/server.py:4383
#, python-format
msgid ""
"PAM authentication is configured but you are not running Gate One as "
"root.  If the pam_service you've selected (%s) is configured to use "
"pam_unix.so for 'auth' (i.e. authenticating against /etc/passwd and "
"/etc/shadow) Gate One will not be able to authenticate all users.  It "
"will only be able to authenticate the user that owns the gateone.py "
"process.pam_service"
msgstr "Аутентификации PAM настроен, но вы не работаете Gate One как корень. Если pam_service вы выбрали ( %s ) настроен на использование pam_unix.so для 'авт' (т.е. проверка подлинности / и т.д. / пароль и / и т.д. / тень) Gate One не сможет проверить подлинность всех пользователей. Это будет только в состоянии проверить подлинность пользователя, которому принадлежит gateone.py process.pam_service"

#: gateone/core/server.py:4392
msgid "Gate One has been configured."
msgstr "Gate One был настроен."

#: gateone/core/server.py:4399
msgid "Listening on Unix socket '{socketpath}'"
msgstr "Прослушивание на Unix сокета '{socketpath}'"

#: gateone/core/server.py:4407 gateone/core/server.py:4425
msgid ""
"You have https_redirect *and* disable_ssl enabled.  Please pick one or "
"the other."
msgstr "Вы должны https_redirect * и * disable_ssl включен. Пожалуйста, выберите один или другой."

#: gateone/core/server.py:4412
msgid "http://{addr}:80/ will be redirected to..."
msgstr "HTTP: // {АДРЕС}: 80 / будете перенаправлены на ..."

#: gateone/core/server.py:4417
msgid "Listening on {proto}{address}:{port}/"
msgstr "Прослушивание на {прото} {адрес}: {порт} /"

#: gateone/core/server.py:4429
msgid "http://*:80/ will be redirected to..."
msgstr "HTTP: // *: 80 / будете перенаправлены на ..."

#: gateone/core/server.py:4432
msgid "Listening on {proto}*:{port}/"
msgstr "Прослушивание на {прото} *: {порт} /"

#: gateone/core/server.py:4460
msgid "Multiprocessing is disabled.  Performance will be sub-optimal."
msgstr "Multiprocessing отключена. Производительность будет неоптимальной."

#: gateone/core/server.py:4470
msgid ""
"Multiprocessing is not functional on this system.  Threading for all "
"async calls."
msgstr "Multiprocessing не работает на этой системе. Threading для всех асинхронных вызовов."

#: gateone/core/server.py:4480
msgid "Shutting down asynchronous processes/threads..."
msgstr "Выключение асинхронных процессов / темы ..."

#: gateone/core/server.py:4486
msgid "Process running with pid "
msgstr "Процесс работает с ПИД "

#: gateone/core/server.py:4492
msgid ""
"Could not listen on {address}:{port} (address:port is already in use by "
"another application)."
msgstr "Не мог слушать на {адрес}: {порт} (адрес: порт уже используется другим приложением)."

#: gateone/core/server.py:4497
msgid ""
"User '{user}' does not have permission to create a process listening on "
"{address}:{port}.  Typically only root can use ports < 1024."
msgstr "Пользователь '{пользователь}' не имеет разрешения на создание сервиса на {адрес}: {порта}. Обычно только корень может использовать порты <1024."

#: gateone/core/server.py:4505
msgid "An error was encountered trying to listen on {address}:{port}..."
msgstr "Произошла ошибка, пытается слушать на {адрес}: {порта} ..."

#: gateone/core/server.py:4509
msgid "Exception was: {0}"
msgstr "Исключение было: {0}"

#: gateone/core/server.py:4511
msgid "Caught KeyboardInterrupt.  Killing sessions..."
msgstr "Оказавшись KeyboardInterrupt. Убийство сессий ..."

#: gateone/core/server.py:4515
msgid "Clearing cache_dir: {0}"
msgstr "Очистка cache_dir: {0}"

#: gateone/core/server.py:4519
msgid "pid file removed."
msgstr "PID файл удаляется."

#: gateone/core/utils.py:334
#, python-format
msgid "Could not write PID file: %s"
msgstr "Не удалось записать PID-файл: %s"

#: gateone/core/utils.py:369
msgid "ERROR: Timeout running shell command"
msgstr "ОШИБКА: Таймаут работает команду оболочки"

#: gateone/core/utils.py:416
#, python-format
msgid "Error generating self-signed SSL key/certificate: %s"
msgstr "Генерирующая Ошибка самозаверяющим ключ SSL / сертификат: %s"

#: gateone/core/utils.py:457
#, python-format
msgid "Generating private key with command: %s"
msgstr "Создание закрытого ключа с помощью команды: %s"

#: gateone/core/utils.py:461
#, python-format
msgid ""
"An error occurred trying to create private SSL key:\n"
"%s"
msgstr "Произошла ошибка при попытке создать закрытый ключ SSL: \ п %s"

#: gateone/core/utils.py:466
#, python-format
msgid "Decrypting private key with command: %s"
msgstr "Расшифровка секретного ключа с помощью команды: %s"

#: gateone/core/utils.py:470
#, python-format
msgid ""
"An error occurred trying to decrypt private SSL key:\n"
"%s"
msgstr "Произошла ошибка при попытке расшифровать секретный ключ SSL: \ п %s"

#: gateone/core/utils.py:475
#, python-format
msgid "Creating CSR with command: %s"
msgstr "Создание CSR с командой: %s"

#: gateone/core/utils.py:479
#, python-format
msgid ""
"An error occurred trying to create CSR:\n"
"%s"
msgstr "Произошла ошибка при попытке создать КСО: \ п %s"

#: gateone/core/utils.py:486
#, python-format
msgid "Generating self-signed certificate with command: %s"
msgstr "Создание собственного сертификата с помощью команды: %s"

#: gateone/core/utils.py:490
#, python-format
msgid ""
"An error occurred trying to create certificate:\n"
"%s"
msgstr "Произошла ошибка при попытке создать сертификат: \ п %s"

#: gateone/core/utils.py:522
msgid ""
"Error: You do not have pyOpenSSL installed.  Please install it (sudo pip "
"install pyopenssl."
msgstr "Ошибка: Вы не установлена ​​pyOpenSSL. Пожалуйста, установите его (Суда пункт установить pyopenssl."

#: gateone/core/utils.py:622
#, python-format
msgid "Could not create directory: %s"
msgstr "Невозможно создать каталог: %s"

#: gateone/core/utils.py:835
#, python-format
msgid ""
"Could not open pid_file (%s).  You *may* have to kill gateone.py manually"
" (probably not)."
msgstr "Не удалось открыть pid_file ( %s ). Вы * может * должны убить gateone.py вручную (вероятно, не)."

#: gateone/core/utils.py:1426
#, python-format
msgid ""
"Error: Gate One does not have the ability to recursively chown %s to uid "
"%s/gid %s.  Please ensure that user, %s has write permission to the "
"directory."
msgstr "Ошибка: Gate One не имеют способность рекурсивно Чаун %s к UID %s / GID %s . Пожалуйста, убедитесь, что пользователь, %s имеет разрешение написать в каталог."

#: gateone/core/utils.py:1541 gateone/core/utils.py:1553
#, python-format
msgid "(saved ~%s bytes minifying %s)"
msgstr "(Сохранены ~ %s байт minifying %s )"

#: gateone/core/utils.py:1545
#, python-format
msgid "slimit failed trying to minify %s"
msgstr "slimit Ошибка при попытке уменьшения размера %s"

#: gateone/core/utils.py:1656
#, python-format
msgid "Could not set supplemental groups: %s"
msgstr "Не удалось установить дополнительные группы: %s"

#: gateone/core/utils.py:1662
#, python-format
msgid "Could not set effective group id: %s"
msgstr "Не удалось установить эффективный идентификатор группы: %s"

#: gateone/core/utils.py:1667
#, python-format
msgid "Could not set effective user id: %s"
msgstr "Не удалось установить эффективный идентификатор пользователя: %s"

#: gateone/core/utils.py:1682
#, python-format
msgid ""
"Running as user/group, \"%s/%s\" with the following supplemental groups: "
"%s"
msgstr "Запуск в качестве пользователя / группы, \ " %s / %s \ "со следующими дополнительных групп: %s"

